name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v1
        name: Cache gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        id: build
        run: ./gradlew build shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Geary Plugin JARs
          path: Geary/build/libs/*.jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: GearyCore Plugin JARs
          path: GearyCore/build/libs/*.jar
