name: Report next version

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  report-next-version:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'major') ||
      contains(github.event.pull_request.labels.*.name, 'minor') ||
      contains(github.event.pull_request.labels.*.name, 'patch')
    steps:
      - name: Find change type
        id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch
      - uses: zwaldowski/semver-release-action@v2
        id: next_version
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          prefix: v
      - name: Show Version
        run: echo Next version at time of running this action will be ${{ steps.next_version.outputs.version }}
      - name: Show Tag
        run: echo Tag will be ${{steps.next_version.outputs.version_tag}}